# copy from https://github.com/rhysd/github-action-benchmark/blob/master/.github/workflows/cpp.yml
# modify code path on line 18, 21
name: C++ Example
on:
  push:
    branches:
      - main

jobs:
  benchmark:
    name: Run C++ benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Benchmark library
        uses: actions/cache@v1
        with:
          path: benchmark
          key: ${{ runner.os }}-googlebenchmark-v1.5.0
      - name: Run benchmark
        run: make json
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: C++ Benchmark
          tool: 'googlecpp'
          output-file-path: benchmark_result.json
          # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/false
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@wangpengx12'
      - name: Run other benchmark
        run: make json-other
      - name: Store Another Benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Other C++ Benchmark
          tool: 'googlecpp'
          out-file-path: benchmark_result_other.json
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@wangpengx12'
